### ISSUE TITLE
Evaluation of data from Flagr (or similar) experiments

### ISSUE THREAD

**Issue by janaab11** [skit-ai/eevee#13]
Since this is also an evaluation, and doesn't have a well-recognised house yet, wanted to add it to eevee. can i just make a PR ?

**Comment by lepisma** [comment]
What kind of evaluations? Can you give example? Is it more about comparison than evaluation?

On September 24, 2021 12:31:25 PM GMT+05:30, Manas ***@***.***> wrote:
>Since this is also an evaluation, and doesn't have a well-recognised house yet, wanted to add it to eevee. can i just make a PR ?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/skit-ai/eevee/issues/13
-- 
Abhinav Tushar
https://lepisma.xyz

Sent from a mobile device. Please excuse my brevity.

**Comment by janaab11** [comment]
right now eevee is giving numbers for a single distribution, this would expand it to two (or more) distributions. a non-ab testing example is the kl divergence between two distributions which could tell you something about, say, the data drift.

The AB testing example is more straightforward. Input is two distributions and output is a formatted report (equivalent of a classification report) that involves average difference of a statistic and corr. confidence on the simpler end, and a detailed plot of confidence vs difference in statistic on the detailed end

**Comment by janaab11** [comment]
The motivation for this comes from the statistical methods sessions i had planned (only the first of which i ended up taking, cos of a lack of interest). This repo should be equipped to handle statistics of distributions, in general, but especially those useful to us internally.

Even in single distributions, eevee only returns point estimates, and not interval estimates. This would be add interval estimate support for two distributions, and hopefully the code will be re-usable for single distributions as well

**Comment by janaab11** [comment]
@lepisma let me know if this is okay. i want to finish this PR over the weekend

**Comment by lepisma** [comment]
Plan looks good. But which exact piece will you add in the package? Do you have some function signatures and use cases that you want to cover?

On September 24, 2021 10:23:04 PM GMT+05:30, Manas ***@***.***> wrote:
***@***.*** let me know if this is okay. i want to finish this PR over the weekend
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/skit-ai/eevee/issues/13#issuecomment-926778949
-- 
Abhinav Tushar
https://lepisma.xyz

Sent from a mobile device. Please excuse my brevity.

**Comment by greed2411** [comment]
this is not in present eevee's scope or interests as of now, please feel free to reopen this PR when the demand is right.
