### ISSUE TITLE
New and improved estimators for mean of a distribution

### ISSUE THREAD

**Issue by janaab11** [skit-ai/eevee#29]
When we calculate the **emperical mean** for a dataset we are trying to estimate the **actual mean** of the underlying distribution. But this is not the best _estimator_. Infact, the emperical mean only estimates the actual mean in the limiting case and the convergence can be arbitrarily slow (depending on your data). There are better (and more explicit) bounds on the convergence of estimators (to the actual mean) when we can assume they satisfy a condition called _sub-Gaussian_. This is satisfied by some estimators - which we want to implement.

For the following to make sense, assume we are working with a (real-valued) dataset of size N:

1. **Median of means** - Divide N points into K groups (randomly), each of (≈) equal size. Calculate the means for each groups and consider the median
2. **Trimmed mean** - Order your dataset, and remove some M points from either end. Consider the mean of the remaining points

The descriptions above are only meant to be suggestive. The actual implementations will have additional parameters that encode the (minimum) confidence level of the calculated estimators. More explicitly, we can choose a threshold `d` and get an upper limit on how far the estimated value is from the actual mean, with probability atleast `1-d`.

---

Replacing the emperical mean might seem like a technicality at first glance, but considering the magnitudes of data at which we work - which isnt very large - these estimators are surprisingly important. WIll add scripts to validate this in the PR.

---

NOTE: This issue comes from a keynote talk at Neurips 2021, titled **Do We Know How to Estimate the Mean?**

**Comment by greed2411** [comment]
this is not in present eevee's scope or interests as of now, please feel free to reopen this PR when the demand is right.
